services:
  bot:
    image: ${BOT_IMAGE:-ghcr.io/hoomanjcode/telegram-yt-bot:latest}
    container_name: youtube-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads
      - ./ssl:/app/ssl
    networks:
      - caddy

networks:
  caddy:
    external: true
