"""HTML templates for the file server landing page and error pages.

This module provides inline-HTML templates rendered by the aiohttp file server.
All CSS is inline so no external assets are needed. The templates share a
consistent design language with a dark theme suitable for a download service.

AI RULE: If you modify this file, you must also update and fix the comments,
docstrings, and descriptions to keep them accurate and current. Every function
must have a descriptive docstring explaining its purpose, parameters, and
return values. Inline comments should explain WHY, not WHAT.
"""

from __future__ import annotations

_STYLES = """
body {{
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen,
        Ubuntu, Cantarell, sans-serif;
    background: linear-gradient(135deg, #0f0c29, #1a1a3e, #24243e);
    color: #e0e0e0;
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}}

.container {{
    text-align: center;
    padding: 2rem;
    max-width: 600px;
}}

.status-dot {{
    display: inline-block;
    width: 12px;
    height: 12px;
    border-radius: 50%;
    background: #4ade80;
    margin-right: 8px;
    box-shadow: 0 0 8px #4ade8080;
    animation: pulse 2s infinite;
}}

@keyframes pulse {{
    0%   {{ opacity: 1; }}
    50%  {{ opacity: 0.5; }}
    100% {{ opacity: 1; }}
}}

h1 {{
    font-size: 4rem;
    margin: 0.5rem 0;
    background: linear-gradient(90deg, #60a5fa, #a78bfa);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
}}

h1.big-error {{
    font-size: 8rem;
    margin: 0;
    line-height: 1;
}}

.subtitle {{
    font-size: 1.1rem;
    color: #94a3b8;
    margin-bottom: 2rem;
}}

.card {{
    background: #1e1e3fcc;
    backdrop-filter: blur(12px);
    border: 1px solid #3b3b6e;
    border-radius: 16px;
    padding: 2rem;
    margin: 1.5rem 0;
}}

.card p {{
    margin: 0.5rem 0;
    color: #cbd5e1;
    line-height: 1.6;
}}

.btn {{
    display: inline-block;
    padding: 0.75rem 1.5rem;
    margin: 0.5rem;
    border-radius: 8px;
    text-decoration: none;
    font-weight: 600;
    transition: all 0.2s ease;
    border: none;
    cursor: pointer;
}}

.btn-primary {{
    background: linear-gradient(90deg, #6366f1, #8b5cf6);
    color: #fff;
}}

.btn-primary:hover {{
    transform: translateY(-2px);
    box-shadow: 0 8px 25px #6366f180;
}}

.btn-secondary {{
    background: #2d2d5e;
    color: #cbd5e1;
}}

.btn-secondary:hover {{
    background: #3b3b6e;
    transform: translateY(-2px);
}}

.files {{
    list-style: none;
    padding: 0;
    margin: 1rem 0;
}}

.files li {{
    padding: 0.6rem 1rem;
    margin: 0.3rem 0;
    background: #16163acc;
    border-radius: 8px;
    display: flex;
    align-items: center;
    justify-content: space-between;
}}

.files a {{
    color: #93c5fd;
    text-decoration: none;
}}

.files a:hover {{
    text-decoration: underline;
}}

.file-size {{
    color: #64748b;
    font-size: 0.85rem;
}}

.footer {{
    margin-top: 2rem;
    font-size: 0.85rem;
    color: #475569;
}}

.error-detail {{
    color: #f87171;
    font-size: 0.9rem;
    margin-top: 1rem;
}}
"""


def _page(title: str, body_html: str) -> str:
    """Wrap the given body HTML in a full HTML document with shared styles."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>{_STYLES}</style>
</head>
<body>
    <div class="container">
        {body_html}
    </div>
</body>
</html>"""


def landing_page(server_host: str, file_count: int = 0) -> str:
    """Render the welcome/landing page for the download domain root.

    This is shown when a user visits the download domain directly in their
    browser (e.g. ``https://dl.example.com/``). It confirms the service is
    running and provides a simple overview.

    Args:
        server_host: The hostname/address of this server.
        file_count: Number of files currently available. Defaults to 0.

    Returns:
        A complete HTML document as a string.
    """
    body = f"""
        <div class="status-dot"></div>
        <span style="color: #4ade80; font-size: 0.9rem;">Service Online</span>

        <h1>📁 Media Server</h1>
        <p class="subtitle">{server_host}</p>

        <div class="card">
            <p>This server hosts downloaded media files generated by the
            <strong>YouTube Downloader Bot</strong>.</p>
            <p>Files are served with resume support, optimized for mobile
            clients, and automatically cleaned up after a few days.</p>
        </div>

        <a href="/files" class="btn btn-primary">Browse Files</a>
        <p style="margin-top: 0.5rem; color: #64748b; font-size: 0.85rem;">
            {file_count} file{'s' if file_count != 1 else ''} available
        </p>

        <div class="footer">
            YouTube Downloader Bot &bull; Educational Project
        </div>
    """
    return _page(f'Media Server — {server_host}', body)


def not_found_page(path: str = '') -> str:
    """Render a friendly 404 Not Found page.

    Args:
        path: The requested path that was not found, shown for context.

    Returns:
        A complete HTML document as a string.
    """
    path_info = f'<p class="error-detail">{path}</p>' if path else ''
    body = f"""
        <h1 class="big-error">404</h1>
        <h2>Lost in Space</h2>
        <p class="subtitle">
            The file or page you're looking for doesn't exist here.
            It may have been deleted or the link might be wrong.
        </p>
        {path_info}
        <div class="card">
            <p>🔍 Files on this server are temporary and expire after a few days.
            If you received a download link from the bot, the file may have
            already been cleaned up — try downloading again from Telegram.</p>
        </div>
        <a href="/" class="btn btn-primary">Go Home</a>
    """
    return _page('404 — Not Found', body)


def forbidden_page() -> str:
    """Render a 403 Forbidden page.

    Shown when a client tries to access a directory listing or a path outside
    the allowed download area.

    Returns:
        A complete HTML document as a string.
    """
    body = """
        <h1 class="big-error">403</h1>
        <h2>Access Denied</h2>
        <p class="subtitle">
            You don't have permission to access this resource.
        </p>
        <div class="card">
            <p>🚫 Directory listing is disabled. Only individual media files
            shared by the bot are accessible through this server.</p>
        </div>
        <a href="/" class="btn btn-primary">Go Home</a>
    """
    return _page('403 — Forbidden', body)


def server_error_page() -> str:
    """Render a 500 Internal Server Error page.

    Shown when an unexpected error occurs while processing a request.

    Returns:
        A complete HTML document as a string.
    """
    body = """
        <h1 class="big-error">500</h1>
        <h2>Something Broke</h2>
        <p class="subtitle">
            An internal server error occurred. The administrator has been
            notified.
        </p>
        <div class="card">
            <p>⚙️ Try refreshing the page in a few seconds. If the problem
            persists, the server may be undergoing maintenance.</p>
        </div>
        <a href="/" class="btn btn-primary">Try Again</a>
    """
    return _page('500 — Server Error', body)


def bad_request_page(reason: str = '') -> str:
    """Render a 400 Bad Request page.

    Args:
        reason: Optional description of why the request was malformed.

    Returns:
        A complete HTML document as a string.
    """
    detail = f'<p class="error-detail">{reason}</p>' if reason else ''
    body = f"""
        <h1 class="big-error">400</h1>
        <h2>Bad Request</h2>
        <p class="subtitle">
            The request could not be understood by the server.
        </p>
        {detail}
        <a href="/" class="btn btn-primary">Go Home</a>
    """
    return _page('400 — Bad Request', body)